// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using DataAccess.Entities;

namespace DataAccess.Contexts
{
    public partial class Db
    {

        [DbFunction("DersOrtalamaHesapla", "dbo")]
        public static decimal? DersOrtalamaHesapla(decimal? not1, decimal? not2, decimal? not3)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("EsitMi", "dbo")]
        public static bool? EsitMi(string deger1, string deger2)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
